services:
  - type: web
    name: filox-api
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    preDeployCommand: npx prisma migrate deploy && npm run db:seed
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_NAME
        value: Admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: filox
      - key: FRONTEND_URL
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAMESITE
        value: "none"
      - key: MAX_FILE_SIZE_MB
        value: "10"
      - key: MAX_FILES_PER_UPLOAD
        value: "5"
      - key: OTP_TTL_MINUTES
        value: "10"
